# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    
    working_directory: ~/

    steps:
      - run: echo "Hello "
  print_world:
    docker:
      - image: circleci/node:13.8.0
    
    working_directory: ~/

    steps:
      - run: echo "World!"
      - run: echo $builder_name

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    
    working_directory: ~/

    steps:
      - run: echo "Hello World" > /tmp/output.txt
      - run: return 1
      - run:
          name: Print on failure
          command: echo "I have run after failure"
          when: on_fail
      - persist_to_workspace:
          root: /tmp
          paths:
            - output*
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    
    working_directory: ~/

    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/output.txt
      - print_pipeline_id


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  
  myjob:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output
